language: node_js

services:
  - docker


after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f Dockerfile -t dadebulba/test_ci_cd.
  - docker push dadebulba/test_ci_cd

